
server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 10m

spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 250MB

google:
  drive:
    client-id: ${GOOGLE_DRIVE_CLIENT_ID:}
    client-secret: ${GOOGLE_DRIVE_CLIENT_SECRET:}
    redirect-uri: ${GOOGLE_DRIVE_REDIRECT_URI:http://localhost:8080/documents/google/callback}
    root-folder-id: ${GOOGLE_DRIVE_ROOT_FOLDER_ID:}
