
server:
  port: ${PORT:8080}
  servlet:
    session:
      timeout: 10m

spring:
  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 250MB

google:
  drive:
    service-account-json-base64: ${GOOGLE_DRIVE_SERVICE_ACCOUNT_JSON_BASE64:}
    root-folder-id: ${GOOGLE_DRIVE_ROOT_FOLDER_ID:}
